### ISSUE TITLE
Ukrainian translation 2020

### ISSUE THREAD

**Issue by gmbox** [wbnns/bitcoinwhitepaper#100]
[Bitcoin_UA.pdf](https://github.com/wbnns/bitcoinwhitepaper/files/5178032/Bitcoin_UA.pdf)
[Bitcoin_UA.zip](https://github.com/wbnns/bitcoinwhitepaper/files/5178033/Bitcoin_UA.zip)

**Comment by wbnns** [comment]
Thank you. Note: There is already a Ukrainian translation in the `Ukrainian` folder.
