### ISSUE TITLE
There is an erratum in the spanish translation of Satoshi Nakamoto's paper

### ISSUE THREAD

**Issue by Amartinez-h** [wbnns/bitcoinwhitepaper#13]
Good afternoon.

I've read both the original paper and the translated to spanish one and I've found that at the ending of the second paragraph of the fourth point (I don't know if it is called that way in a paper, but, hopefully, you will understand me).
In the original one it states that every block after the one altered will have to be redone ("_As later blocks are chained after it, the work to change the block would include **redoing all the blocks after it**._"), meanwhile in the spanish translation it states quite the opposite, as it reads that it is the previous ones which will have to be redone. ("_A medida que bloques posteriores se encadenen tras él, el trabajo para cambiar un bloque incluiría **rehacer todos los bloques anteriores**._").
I hope it can be fixed, so spanish readers won't get all confused there, as the text states the opposite from what it should be stating.

Cheers!

**Comment by khendraw** [comment]
Hello thank you for your advise. Any Spanish translator can help verify it?

**Comment by khendraw** [comment]
I don't speak Spanish but the Google Translate the _"A medida que bloques posteriores se encadenen tras él, el trabajo para cambiar un bloque incluiría rehacer todos los bloques anteriores."_ as on the Spanish translation document to _"As subsequent blocks are chained after it, the job to change a block would include redoing all the previous blocks."_ in English - which has the correct meaning to the original English version. This means that the block cannot be changed without redoing the work.
