### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by marcdzfr** [wbnns/bitcoinwhitepaper#20]
I translated perfectly your whitepaper into French.

Here it is :
https://www.dropbox.com/s/7e3nu7tacep107s/bitcoin_fr.pdf?dl=0

Can you add it to your page?
https://bitcoin.org/en/bitcoin-paper

Thank you.

**Comment by wbnns** [comment]
Thanks for doing this - would you be interested in reviewing/editing the current French version in the repository? Once that is done, we can move the PDF over to Bitcoin.org.
