### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tderflinger** [wbnns/bitcoinwhitepaper#23]
Hello!

What is the license of the Bitcoin Whitepaper? 
I am considering translating to German.

Kind regards,
-Tommy

**Comment by dhimmel** [comment]
As far as I know, the whitepaper doesn't specify any specific license, and would thus be all rights reserved.

However, it's possible it's available under an MIT license from https://bitcoin.org/en/bitcoin-paper. IANAL, but it seems unlikely Satoshi would return to claim copyright infringement on the whitepaper. Still frustrating though that it's not explicitly available under say a CC BY or CC0 license.

**Comment by besold** [comment]
The German translation is done and uploaded to <a href="https://github.com/besold/bitcoinwhitepaper" target="_blank" title="BitCoin WhitePaper German">GitHub</a>. I just don't know how to make it visible on <a href="https://bitcoin.org/en/bitcoin-paper" target="_blank" title="BitCoin.org WhitePapers">bitcoin.org</a>...

**Comment by wbnns** [comment]
@tderflinger @besold Would either of you be interested in reviewing/editing the German version that's currently in the repository? The formatting and style also needs to be updated to match the original whitepaper. Once this is done we can move it over to Bitcoin.org.
