### ISSUE TITLE
I have a serious question.

### ISSUE THREAD

**Issue by OmarHamdy** [wbnns/bitcoinwhitepaper#24]
I'm willing to translate the bitcoin paper to my language, But I'm wondering where should I upload or send it after I'm done?

**Comment by besold** [comment]
I haven't really found an answer to that question myself. But you should start by checking, if there isn't already a translation into your language. There are <a href="https://github.com/besold/bitcoinwhitepaper/network/members" target="_blank" title="Forks from saivann/bitcoinwhitepaper">42 projects</a> that forked from forked from saivann/bitcoinwhitepaper, which appears to be abandoned, anyway.
Go through them and see if it already exists in you language. If not, at least you can add it there. You can access the site by clicking <a href="https://github.com/besold/bitcoinwhitepaper/network/members" target="_blank" title="">here</a> or by following the path:

<a href="https://bitcoin.org/en/bitcoin-paper" target="_blank" title="BitCoin WhitePaper">BitCoin.org Whitepaper Page</a> &rarr; <a href="https://github.com/saivann/bitcoinwhitepaper" target="_blank" title="BitCoin WhitePaper Repository on GitHub">GitHub saivann/bitcoinwhitepaper</a> &rarr; <a href="https://github.com/saivann/bitcoinwhitepaper/network" target="_blank" title="">Project Forks</a> &rarr; <a href="https://github.com/saivann/bitcoinwhitepaper/network/members" target="_blank" title="Forks">Forks</a>

**Comment by wbnns** [comment]
Hello, this repository is active again. Apologies for the lapse. All you need to do is submit pull requests with ODT versions of the translations. From there we can review them, them convert them to PDFs to add to Bitcoin.org.
