### ISSUE TITLE
Translation in Korean

### ISSUE THREAD

**Issue by imc84** [wbnns/bitcoinwhitepaper#30]
Last year, I did translate full text in bitcoin.pdf file without style and format data in Korean. In fact it was done a couple of months ago, and I shared it with my friends. I just replaced the english text to my translated sentences and paragraphs. It doesn't have good layout.

Recently, I found this repository and the bitcoin.odt document with actual style and format data. By using the original bitcoin.odt document, I'm remaking my translated version of it. For doing it, I've just sign up github and forked this reporsitory. I'm going to upload my version as soon as possible, then I'll refine its words and sentences fit to context with my colleagues, and pull request the final version.

However, I have a small problem.

---

I'm using the last LibreOffice 5 version on Windows 10 for editing the original bitcoin.odt document here. When I open the file, some typos and glyphs in document look untidy and uncomfortable a little. I think the file's format and style data aren't suitable for the office version or my OS locale environment, maybe.

I can fix some of them, but I can't fix the untidy characters in equation object. I'm stuck here. If you have the way to adjust precisely the location of the characters in equation object or other technic, let me know please. Thank you.

---

I've just solved the problem above. I installed the old LibreOffice 3 version released 4 years ago and opened original file, it doesn't showed nothing special crack on style, format, and layout.

**Comment by wbnns** [comment]
Thanks for working on this!
