### ISSUE TITLE
A typo in Russian translation

### ISSUE THREAD

**Issue by 1640max** [wbnns/bitcoinwhitepaper#33]
Hello! There is a typo in Russian version of the document. The very first picture states that owner 2's signature must be checked with owner 1's public key. That's wrong, isn't it?

**Comment by nik0x01** [comment]
Already corrected here! 
I hope soon to be corrected on the website.

**Comment by khendraw** [comment]
The correction is already merged and will be on the website soon.
Thank you for working on this.
