### ISSUE TITLE
BitCoin Whitepaper Translation

### ISSUE THREAD

**Issue by besold** [wbnns/bitcoinwhitepaper#34]
Why is the last activity here been registered three years ago? I did a <a href="https://github.com/besold/bitcoinwhitepaper" target="_blank" title="BitCoin WhitePaper German">German translation</a> of the BitCoin Whitepaper, how do I proceed?

**Comment by wbnns** [comment]
@besold Thank you for working on this and apologies for the delays. This repository is active again.
