### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Balaxi** [wbnns/bitcoinwhitepaper#35]
Hi,

We prepared the bitcoin white paper in Hungarian.

I attached the word doc and the pdf as well. If it requires further polishing, please let us know. 

Sincerely,

Balazs Fekete & the [Bitcoin Bazis](http://www.bitcoinbazis.hu/) team

[Szatosi Nakamoto Egy P2P elektronikus készpénzrendszer.docx](https://github.com/saivann/bitcoinwhitepaper/files/1678139/Szatosi.Nakamoto.Egy.P2P.elektronikus.keszpenzrendszer.docx)

[Szatosi Nakamoto Egy P2P elektronikus készpénzrendszer.pdf](https://github.com/saivann/bitcoinwhitepaper/files/1678143/Szatosi.Nakamoto.Egy.P2P.elektronikus.keszpenzrendszer.pdf)

**Comment by wbnns** [comment]
Hello, could you please open a pull request, adding it to the repository in ODT format?
