### ISSUE TITLE
I just found there is Chinese version of bitcoin whtie paper,

### ISSUE THREAD

**Issue by caesarchad** [wbnns/bitcoinwhitepaper#40]
Hi, Guys
I just found, there is no Chinese version of bitcoin white paper, do you mind if I take the job of translating it to Chinese?

**Comment by packagewjx** [comment]
#37 is a Chinese version.
We can improve it.

**Comment by wbnns** [comment]
Please feel free to submit a pull request to further improve the Chinese version. Thanks for the help!
