### ISSUE TITLE
Submit Translation

### ISSUE THREAD

**Issue by christahir** [wbnns/bitcoinwhitepaper#43]
Hi, how can I submit my home country language translation of the whitepaper?

Thanks

**Comment by christahir** [comment]
Hello, will there be anyone in charge that can help with the uploading issue?

I want to submit translation in Indonesian.

Thanks

**Comment by wbnns** [comment]
@christahir Hello, you need to open a pull request adding the translation in ODT format. In case helpful, here's documentation on how to open a pull request:
https://help.github.com/articles/about-pull-requests/

If you have any other questions, please let us know.

**Comment by christahir** [comment]
Thanks for the reply @wbnns
I have created the pull request.
