### ISSUE TITLE
Arabic Translation of Satoshi's Paper

### ISSUE THREAD

**Issue by NadaHouri** [wbnns/bitcoinwhitepaper#47]
Hello,
I am inquiring about the possible translation of Satoshi's paper to Arabic.
Please advise.

**Comment by khendraw** [comment]
Hi,
Thank you for your interest in translating the paper to Arabic.
Sure, just make a your branch and upload the translated file with the file name format of bitcoin_ar.odt and make a pull request once it is done. We will review and merge the translation. Just remember to follow the guideline on the README.md
Thank you.
