### ISSUE TITLE
Bitcoin: A Peer-to-Peer Electronic Cash System. Tranlation to Spanish (Mexico).

### ISSUE THREAD

**Issue by Osvaldo111** [wbnns/bitcoinwhitepaper#53]
Hello,

I wonder if I can help to translate the "Bitcoin: A Peer-to-Peer Electronic Cash System" document to Spanish (Mexico). Let me know your comments.  

Thank you.

**Comment by khendraw** [comment]
Hi, sure you can. 
Please make sure you read the 
[README.md](https://github.com/wbnns/bitcoinwhitepaper/blob/master/README.md)
Thank you and if you have any further question please don't hesitate to contact me.

**Comment by Osvaldo111** [comment]
Thank you. I will let you know when I'm done with the document.
