### ISSUE TITLE
New Bitcoin Whitepaper

### ISSUE THREAD

**Issue by d1m1tza** [wbnns/bitcoinwhitepaper#56]
Hello Bitcoin Development Team,

I would like to present you a version of Bitcoin's whitepaper that could would give a more friendly approach to its readers. I left the original writing and only redesigned the graphic illustrations and its format.  I understand that the Academic version of the Whitepaper has a certain emotion attached to it, but it would be nice to have an alternative.

This is part of a case-study in [Goldpapers.io](https://goldpapers.io)  - A writing and designing whitepaper service for blockchain projects. 
[New Bitcoin Whitepaper.pdf](https://github.com/wbnns/bitcoinwhitepaper/files/2534818/New.Bitcoin.Whitepaper.pdf)

Please do let me know your thoughts.

**Comment by khendraw** [comment]
Hello,
Thank you for coming to us with this, we really appreaciate it. 
Currently we are focusing on translating the whitepaper to be available worldwide, but we will learn about your suggestion.
