### ISSUE TITLE
a way for distributing the korean translated version

### ISSUE THREAD

**Issue by imc84** [wbnns/bitcoinwhitepaper#61]
I have my translation in Korean for the bitcoin whitepaper and it is on here[1] and there[2] in PDF files named 'bitcoin_ko'. I want to know whether there is a way for distributing them on the bitcoin-dot-org webpage[3] as the other PDF files in Español, Italiano, Русский, and Svenska there. If I could upload the korean version on there, what should I do? I found a repo and the directory in there related on this topic[4], but I think it is not shown exactly for distributing files on bitcoin-dot-org page.

[1] https://github.com/wbnns/bitcoinwhitepaper/tree/master/Korean
[2] https://github.com/imc84/bitcoinwhitepaper/
[3] https://bitcoin.org/en/bitcoin-paper
[4] https://github.com/bitcoin-dot-org/bitcoin.org/tree/master/files/bitcoin-paper

**Comment by khendraw** [comment]
Hello there,
Unfortunately the only way to include the whitepaper translation on bitcoin-dot-org website is done by the website maintaners. I will check this issue out since the pdf files are ready.

**Comment by cryptohakka** [comment]
This will be a common issue among each country's whitepaper. Many whitepapers are ready but have not been uploaded. If there is any reason not to upload them website maintainers have to explain it. It's very easy task to upload them.

**Comment by wbnns** [comment]
Hello, thank you all for your patience. The PR to add the various translations and make them live has been opened.
