### ISSUE TITLE
Bosnian/Croatian/Serbian translation

### ISSUE THREAD

**Issue by IrenaSA** [wbnns/bitcoinwhitepaper#65]
Hello,
I just wont to inform you that I will make translation of  "Bitcoin: A Peer-to-Peer Electronic Cash System" into Bosnian/Croatian/Serbian Languages (ex-Yugoslav Language), for my own needs. When I am done I will submit/upload the translation in PDF file.
Is that OK?

Kind Regards

**Comment by khendraw** [comment]
Thank you for participating on the Bitcoin whitepaper translation,
Please follow the instruction on Readme.md and the .odt file accompanying the .pdf file is also needed. You can contact me if you have some difficulty in uploading the result.

Regards,

**Comment by wishxy** [comment]
Hi Irena, please let us know if you have finished translation of Bitcoin white paper as we are already in the process of translating in Serbian/Bosnian/Croatian and I just now find out about this repository.

**Comment by IrenaSA** [comment]
I translated up to chapter 8th...do not know when I will finish it.. So if
you have finished translation go ahead and submit it.
I would like to see it as well...

Irena Šabović
*Poslovna administracija/Business Administration*

Tel.: +387 33 563 15 <%2B387%2033%20563%20156>0

Mob: 060 349 0835

E-mail: irena.sabovic@bbs.ba <damir.skenderovic@bbs.ba>



*Bosnien Business Systems d.o.o. Sarajevo*

Kranjčevićeva 39, 71000 Sarajevo, BiH

Centrala: +387 33 563 150

Fax: +387 33 563 154

Web: www.bbs.ba

**Comment by wbnns** [comment]
There is now a Croatian translation available in the `Croatian` folder.
