### ISSUE TITLE
Bitcoin whitepaper in Bulgarian

### ISSUE THREAD

**Issue by mradkov** [wbnns/bitcoinwhitepaper#67]
Translation in Bulgarian is started. Will send PR as soon as its ready.

**Comment by khendraw** [comment]
Thank you for your participation. Please check README.MD for directions.

**Comment by Relaxo143** [comment]
> Translation in Bulgarian is started. Will send PR as soon as its ready.

Are you still working on it? If you have abandoned the idea I will gladly translate it.

**Comment by mradkov** [comment]
It's ready since a while now. I'll be making a PR when I find some free time this week.

**Comment by khendraw** [comment]
Thank you guys, looking forward for the PR.
