### ISSUE TITLE
BTC Nederlands translation

### ISSUE THREAD

**Issue by Giftbitnl** [wbnns/bitcoinwhitepaper#69]
I've uploaded a pull request (Nederlands) with the .odt and .pdf included.

**Comment by khendraw** [comment]
Hello, thank you for your contribution. Unfortunately I don't see any pull request on the wbnns/bitcoinwhitepaper 
If you have any difficulties, you can always contact me for assistance.
Thanks

**Comment by Giftbitnl** [comment]
Good day,
You are right, my bad. It should be visible now.

**Comment by khendraw** [comment]
Thank you for your contribution. 
The PR is merged - I did some file renaming and organize it to a folder.
