### ISSUE TITLE
Norwegian Bitcoin Whitepaper

### ISSUE THREAD

**Issue by sandwes** [wbnns/bitcoinwhitepaper#76]
I've been working on a Norwegian translation for the Bitcoin whitepaper for the Norwegian crypto site Kryptografen, but I'm not sure how to upload it. I've attached the PDF and [here is the link to the .odt file.](https://www.jottacloud.com/s/066e67d6ddb43004701908117188e2b657f)

[bitcoin_nob.pdf](https://github.com/wbnns/bitcoinwhitepaper/files/3492282/bitcoin_nob.pdf)

**Comment by khendraw** [comment]
Thank you for your participation in translating the Bitcoin whitepaper to Norwegian.
I have upload the file to the repository.
