### ISSUE TITLE
Wrong name on Norwegian whitepaper - Should say "Norsk (Bokmål)"

### ISSUE THREAD

**Issue by sandwes** [wbnns/bitcoinwhitepaper#79]
Hello!

On the Norwegian translation on bitcoin.org it says "Bokmål" as the language, but it should be "Norsk (Bokmål)". Since "Bokmål" is the type of Norwegian it's written on, not the language itself.

**Comment by wbnns** [comment]
@sandwes 

Thanks! We've opened a PR to make the correction:
https://github.com/bitcoin-dot-org/bitcoin.org/pull/3126
