### ISSUE TITLE
Bitcoin White Paper in romanian

### ISSUE THREAD

**Issue by IkeGDB** [wbnns/bitcoinwhitepaper#81]
Bitcoin White Paper in romanian language is finish. Please check out at https://github.com/IkeGDB/Bitcoin

**Comment by wbnns** [comment]
@IkeGDB Thank you. Could you please provide the source file (odt, doc, or other) in addition to the pdfs?

**Comment by IkeGDB** [comment]
Sure, doc version is uploaded.

**Comment by khendraw** [comment]
Hi,
I just add the files (bitcoin_ro.odt & bitcoin_ro.pdf) on the [repository](https://github.com/wbnns/bitcoinwhitepaper) based on the @IkeGDB 's [files](https://github.com/IkeGDB/Bitcoin).
Please check and should there any revision needed, it can be done from the repository.

Thank you for your participation.
