### ISSUE TITLE
Translation to Hebrew

### ISSUE THREAD

**Issue by ZeevBB** [wbnns/bitcoinwhitepaper#83]
Hi, I noticed that the white paler has not been translated to Hebrew, I am ready to do that but don't understand the process.  I didn't find anywhere instruction that will let me go forward.
Best regards,
Zeev Shilor

**Comment by khendraw** [comment]
Hello,
Thank you for your participation.
You can find the instruction [here](https://github.com/wbnns/bitcoinwhitepaper/blob/master/README.md)

Please just let me know if you need anything else regarding the translation process.

Thanks

**Comment by ZeevBB** [comment]
Hi,

 

The Hebrew copy is ready to go in ODT format. How do I get it back to github in the right way?

Also, I couldn't figure out how to save a copy as PDF as this option is not available in LibreOffice Writer?

 

Regards,

 

Ze'ev

**Comment by wbnns** [comment]
@ZeevBB Great, thank you. Can you please email it to will@bitcoin.org?

**Comment by ZeevBB** [comment]
As per previous correspondence, attached please find the Hebrew version of Satoshi's Bible. I will be working (in Transifex) on the translation of  A. Antonopoulos' Mastering Bitcoin. The same translation will be included also there.

 

Regards,

 

Ze'ev

**Comment by khendraw** [comment]
Hi @ZeevBB I believe you will need to create a new email directly to will@bitcoin.org since you can't attach file(s) within the github notification email.
Thanks

**Comment by wbnns** [comment]
@ZeevBB Thanks again.

@khendraw Thank you too; I received his email and have sent it to you on Telegram.

**Comment by wbnns** [comment]
[PDF: Hebrew translation](https://github.com/wbnns/bitcoinwhitepaper/files/3819626/whitepaper_translated.pdf)

**Comment by ZeevBB** [comment]
Thank you, I see a few glitches needing correction. I will send you a revision shortly.

 

Regards,

 

Ze'ev

**Comment by ZeevBB** [comment]
In the PDF I see in section one, the first paragraph, a different font while the original is correct, so I am not sure what to do about it. Meanwhile I am reading the rest to pick up glitches, if any.

**Comment by wbnns** [comment]
@ZeevBB Ok, thank you.

**Comment by ZeevBB** [comment]
Sent you to the other email address the corrected and the associated pdf which I figured out how to generate, All is fine and ready to go.

 

Regards,

 

Ze'ev

**Comment by khendraw** [comment]
Hebrew translation verified and added to repository.
Thank you for your contribution.

https://github.com/wbnns/bitcoinwhitepaper/tree/master/Hebrew
