### ISSUE TITLE
Persian Whitepaper on bitcoin.org

### ISSUE THREAD

**Issue by ZeeAmini** [wbnns/bitcoinwhitepaper#85]
Hi :)

Thanks for adding the whitepaper to the website :)
There's an error in the language writing at this page: 
https://bitcoin.org/en/bitcoin-paper
it's not فارسیة. the letter ة doesn't exist in Persian.

Pls edit it to پارسی or فارسی as in this wikipedia page:
https://fa.wikipedia.org/wiki/%D8%B2%D8%A8%D8%A7%D9%86_%D9%81%D8%A7%D8%B1%D8%B3%DB%8C

Thank you

![photo_2019-11-27_12-29-39](https://user-images.githubusercontent.com/56531863/69915742-b8a17f00-1467-11ea-8830-3e1ca10ec728.jpg)

**Comment by wbnns** [comment]
@ZeeAmini 

Hello, thanks for letting us know. We've made the [fix](https://github.com/bitcoin-dot-org/bitcoin.org/pull/3205), which will be live on the site, soon.
