### ISSUE TITLE
Hindi Paper

### ISSUE THREAD

**Issue by bitcoingullak** [wbnns/bitcoinwhitepaper#90]
I have written paper in Hindi, 2 pages left. How would I upload it for everyone to access?

**Comment by khendraw** [comment]
Hello, thank you for contributing. You can upload by creating a folder on repository (Hindi) and put the files in the folder.

If you need any assistance in uploading the files please mention me and will assist you.

**Comment by bitcoingullak** [comment]
Hello, 

Thank you for your message,, I think I have done it. Please check if done correctly.

**Comment by khendraw** [comment]
Hello,
First thing first you need to pull the [original repository](https://github.com/wbnns/bitcoinwhitepaper) to your own repository. 
Then you can make the changes on your own repository.
After the changes are done you can make a pull request to the original repository.

Or if you find it too complicated, then you can just send me the files and I will help you.

**Comment by bitcoingullak** [comment]
https://github.com/wbnns/bitcoinwhitepaper/pull/92

Please check if that is correct way of doing it or not? if not here I have attached it. 

Thank you. 

[Bitcoin_Hindi.pdf](https://github.com/wbnns/bitcoinwhitepaper/files/4498468/Bitcoin_Hindi.pdf)

**Comment by khendraw** [comment]
Hello,

Can you also provide the .odt file?
And please use the standard file name
bitcoin_hi.odt
bitcoin_hi.pdf
inside the Hindi folder.

Thanks

**Comment by bitcoingullak** [comment]
New pull request?

**Comment by khendraw** [comment]
Yes, you can make another pull request after the revision and add the .odt file.
Thanks

**Comment by bitcoingullak** [comment]
Please check

**Comment by khendraw** [comment]
Hello,
I see no new pull request yet. Probably you haven't made a push?

Thanks

**Comment by bitcoingullak** [comment]
Hello, 

Just pushed. 

Thanks.

**Comment by khendraw** [comment]
All is OK now. Will review the translation later.
Thank you for your contribution.
