### ISSUE TITLE
Albanian translation

### ISSUE THREAD

**Issue by endriwcela** [wbnns/bitcoinwhitepaper#97]
Hello everybody,
I just want to inform you that I will translate "Bitcoin: A Peer-to-Peer Electronic Cash System" into Albanian language, so all Albanian speaking community can have access to it. 

Warm Regards,

**Comment by TonyXhufi** [comment]
any progress on translating the WP...happy to help with translating into Albanian thanks T

**Comment by wbnns** [comment]
Closing since we now have an Albanian translation. Thank you all.
